import { BaseTexture } from '@babylonjs/core/Materials/Textures/baseTexture';
import { MaterialDefines } from '@babylonjs/core/Materials/materialDefines';
import { UniformBuffer } from '@babylonjs/core/Materials/uniformBuffer';
import { Scene } from '@babylonjs/core/scene';
import { Texture } from '@babylonjs/core/Materials/Textures/texture';
import { Vector2, Vector3, Vector4 } from '@babylonjs/core/Maths/math.vector';
import { IAnimatable } from '@babylonjs/core/Animations';
import { MaterialPluginBase } from '@babylonjs/core/Materials/materialPluginBase';
import { PBRMaterial } from '@babylonjs/core/Materials/PBR/pbrMaterial';
export declare class CustomShaderMaterial extends PBRMaterial {
    universalMaterial: boolean;
    private _defines;
    private _uniforms;
    private _samplers;
    private _attributes;
    private _textures;
    private _vectors4;
    private _vectors3;
    private _vectors2;
    private _floats;
    private _bools;
    private _ubos;
    protected shader: string;
    protected plugin: MaterialPluginBase;
    constructor(name: string, scene: Scene);
    addAttribute(attributeName: string): void;
    checkUniform(uniformName: string, type: string, value?: any): void;
    checkSampler(samplerName: string, texture?: any): void;
    addTextureUniform(name: string, texture: Texture): CustomShaderMaterial;
    setTextureValue(name: string, texture: Texture): CustomShaderMaterial;
    getTextureValue(name: string): Texture;
    addVector4Uniform(name: string, value: Vector4): CustomShaderMaterial;
    setVector4Value(name: string, value: Vector4): CustomShaderMaterial;
    getVector4Value(name: string): Vector4;
    addVector3Uniform(name: string, value: Vector3): CustomShaderMaterial;
    setVector3Value(name: string, value: Vector3): CustomShaderMaterial;
    getVector3Value(name: string): Vector3;
    addVector2Uniform(name: string, value: Vector2): CustomShaderMaterial;
    setVector2Value(name: string, value: Vector2): CustomShaderMaterial;
    getVector2Value(name: string): Vector2;
    addFloatUniform(name: string, value: number): CustomShaderMaterial;
    setFloatValue(name: string, value: number): CustomShaderMaterial;
    getFloatValue(name: string): number;
    addBoolUniform(name: string, value: boolean): CustomShaderMaterial;
    setBoolValue(name: string, value: boolean): CustomShaderMaterial;
    getBoolValue(name: string): boolean;
    getAnimatables(): IAnimatable[];
    getActiveTextures(): BaseTexture[];
    hasTexture(texture: BaseTexture): boolean;
    getCustomUniforms(wgsl: boolean): CustomUniformProperty[];
    getCustomSamplers(): string[];
    getCustomAttributes(): string[];
    getCustomVertexCode(wgsl: boolean): string;
    getCustomFragmentCode(wgsl: boolean): string;
    prepareCustomDefines(defines: MaterialDefines): void;
    updateCustomBindings(effect: UniformBuffer): void;
    protected buildUniformProperty(uniformName: string, uniformType: string, uniformValue: any): void;
}
export type CustomUniformProperty = {
    name: string;
    size: number;
    type: string;
    arraySize?: number;
};
//# sourceMappingURL=customshadermaterial.d.ts.map