services:
  certificates:
    image: alpine/openssl
    volumes:
      - ./secrets/ssl:/ssl
    command:
      - req
      - -x509
      - -nodes
      - -days
      - "365"
      - -newkey
      - rsa:2048
      - -keyout
      - /ssl/selfsigned.key
      - -out
      - /ssl/selfsigned.crt
      - -subj
      - /C=FR/ST=Auvergne-Rhône-Alpes/L=Brignais/O=42/CN=brappo
  fastify-prod:
    build:
      context: ./fastify/
      additional_contexts:
        babylonjs-toolkit: ../mackeyk24
    volumes:
      - databases:/app/databases/
    environment:
      - PROFILE=${PROFILE:-prod} 
    profiles: [
      "prod",
    ]
    env_file:
      - ./fastify/app_src/.env
  fastify-dev:
    build:
      context: ./fastify/
      additional_contexts:
        babylonjs-toolkit: ../mackeyk24
    volumes:
      - backend:/app/dev/
      - databases:/app/databases/
    environment:
      - PROFILE=${PROFILE:-dev} 
    profiles: [
      "dev"
    ]
    env_file:
      - ./fastify/app_src/.env
  nginx:
    build:
      context: ./nginx/
      additional_contexts:
        babylonjs-toolkit: ../mackeyk24
    ports:
      - "8080:443"
    profiles: [
      "prod"
    ]
    secrets:
      - ssl_key
      - ssl_crt
    depends_on:
      - fastify-prod
  vite:
    build:
      context: ./vite/
      additional_contexts:
        babylonjs-toolkit: ../mackeyk24
    ports:
      - "8080:443"
    volumes:
      - frontend:/app/frontend/
      - shared:/app/shared/
    profiles: [
      "dev"
    ]
    secrets:
      - ssl_key
      - ssl_crt
    depends_on:
      - fastify-dev

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      device: ../src/frontend/dev/
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: ./fastify/app_src/dev/
      o: bind
  shared:
    driver: local
    driver_opts:
      type: none
      device: ../src/shared/
      o: bind
  databases:
    driver: local

secrets:
  ssl_crt:
    file: ./secrets/ssl/selfsigned.crt
  ssl_key:
    file: ./secrets/ssl/selfsigned.key
